'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MESPdLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It could not be finished.
        '''</summary>
        Friend ReadOnly Property ErrorCanNotFinish() As String
            Get
                Return ResourceManager.GetString("ErrorCanNotFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It could not be started.
        '''</summary>
        Friend ReadOnly Property ErrorCanNotProcessStart() As String
            Get
                Return ResourceManager.GetString("ErrorCanNotProcessStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It could not be started.
        '''</summary>
        Friend ReadOnly Property ErrorCanNotStart() As String
            Get
                Return ResourceManager.GetString("ErrorCanNotStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It has been finished.
        '''</summary>
        Friend ReadOnly Property ErrorFinished() As String
            Get
                Return ResourceManager.GetString("ErrorFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login error.
        '''</summary>
        Friend ReadOnly Property ErrorLogin() As String
            Get
                Return ResourceManager.GetString("ErrorLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material is incorrect.
        '''</summary>
        Friend ReadOnly Property ErrorMaterialIncorrect() As String
            Get
                Return ResourceManager.GetString("ErrorMaterialIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No results of previous process. Do you want to continue?.
        '''</summary>
        Friend ReadOnly Property ErrorNoResultsPreviousProcess() As String
            Get
                Return ResourceManager.GetString("ErrorNoResultsPreviousProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password is required.
        '''</summary>
        Friend ReadOnly Property ErrorNotInputPassword() As String
            Get
                Return ResourceManager.GetString("ErrorNotInputPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User ID is required.
        '''</summary>
        Friend ReadOnly Property ErrorNotInputUserId() As String
            Get
                Return ResourceManager.GetString("ErrorNotInputUserId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It does not start.
        '''</summary>
        Friend ReadOnly Property ErrorNotStart() As String
            Get
                Return ResourceManager.GetString("ErrorNotStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It has been started.
        '''</summary>
        Friend ReadOnly Property ErrorProcessStarted() As String
            Get
                Return ResourceManager.GetString("ErrorProcessStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration error.
        '''</summary>
        Friend ReadOnly Property ErrorRegister() As String
            Get
                Return ResourceManager.GetString("ErrorRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serial No creation error.
        '''</summary>
        Friend ReadOnly Property ErrorSerialNoCreation() As String
            Get
                Return ResourceManager.GetString("ErrorSerialNoCreation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please input the serial No.
        '''</summary>
        Friend ReadOnly Property ErrorSerialRequired() As String
            Get
                Return ResourceManager.GetString("ErrorSerialRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It has been started.
        '''</summary>
        Friend ReadOnly Property ErrorStarted() As String
            Get
                Return ResourceManager.GetString("ErrorStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to log out?.
        '''</summary>
        Friend ReadOnly Property LogOutConfirm() As String
            Get
                Return ResourceManager.GetString("LogOutConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None data.
        '''</summary>
        Friend ReadOnly Property NoneData() As String
            Get
                Return ResourceManager.GetString("NoneData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finish.
        '''</summary>
        Friend ReadOnly Property ProcessProductStatusComplete() As String
            Get
                Return ResourceManager.GetString("ProcessProductStatusComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ―.
        '''</summary>
        Friend ReadOnly Property ProcessProductStatusNone() As String
            Get
                Return ResourceManager.GetString("ProcessProductStatusNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Working.
        '''</summary>
        Friend ReadOnly Property ProcessProductStatusStart() As String
            Get
                Return ResourceManager.GetString("ProcessProductStatusStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finish.
        '''</summary>
        Friend ReadOnly Property ProcessStatusComplete() As String
            Get
                Return ResourceManager.GetString("ProcessStatusComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ―.
        '''</summary>
        Friend ReadOnly Property ProcessStatusNone() As String
            Get
                Return ResourceManager.GetString("ProcessStatusNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend ReadOnly Property ProcessStatusStart() As String
            Get
                Return ResourceManager.GetString("ProcessStatusStart", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
