'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5485
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MESPdLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  It could not be finished に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorCanNotFinish() As String
            Get
                Return ResourceManager.GetString("ErrorCanNotFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  It could not be started に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorCanNotProcessStart() As String
            Get
                Return ResourceManager.GetString("ErrorCanNotProcessStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  It could not be started に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorCanNotStart() As String
            Get
                Return ResourceManager.GetString("ErrorCanNotStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  It has been finished に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorFinished() As String
            Get
                Return ResourceManager.GetString("ErrorFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Login error に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorLogin() As String
            Get
                Return ResourceManager.GetString("ErrorLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Material is incorrect に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorMaterialIncorrect() As String
            Get
                Return ResourceManager.GetString("ErrorMaterialIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  No results of previous process. Do you want to continue? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorNoResultsPreviousProcess() As String
            Get
                Return ResourceManager.GetString("ErrorNoResultsPreviousProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Password is required に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorNotInputPassword() As String
            Get
                Return ResourceManager.GetString("ErrorNotInputPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  User ID is required に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorNotInputUserId() As String
            Get
                Return ResourceManager.GetString("ErrorNotInputUserId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  It does not start に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorNotStart() As String
            Get
                Return ResourceManager.GetString("ErrorNotStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  It has been started に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorProcessStarted() As String
            Get
                Return ResourceManager.GetString("ErrorProcessStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Registration error に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorRegister() As String
            Get
                Return ResourceManager.GetString("ErrorRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Serial No creation error に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorSerialNoCreation() As String
            Get
                Return ResourceManager.GetString("ErrorSerialNoCreation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please input the serial No に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorSerialRequired() As String
            Get
                Return ResourceManager.GetString("ErrorSerialRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  It has been started に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorStarted() As String
            Get
                Return ResourceManager.GetString("ErrorStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Do you want to log out? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LogOutConfirm() As String
            Get
                Return ResourceManager.GetString("LogOutConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  None data に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NoneData() As String
            Get
                Return ResourceManager.GetString("NoneData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Finish に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ProcessProductStatusComplete() As String
            Get
                Return ResourceManager.GetString("ProcessProductStatusComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ― に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ProcessProductStatusNone() As String
            Get
                Return ResourceManager.GetString("ProcessProductStatusNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Working に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ProcessProductStatusStart() As String
            Get
                Return ResourceManager.GetString("ProcessProductStatusStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Finish に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ProcessStatusComplete() As String
            Get
                Return ResourceManager.GetString("ProcessStatusComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ― に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ProcessStatusNone() As String
            Get
                Return ResourceManager.GetString("ProcessStatusNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Start に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ProcessStatusStart() As String
            Get
                Return ResourceManager.GetString("ProcessStatusStart", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
